# Generated by Django 4.2.11 on 2026-05-15 20:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('homeowner', 'Homeowner'), ('contractor', 'Contractor'), ('student', 'Architecture Student'), ('admin', 'Administrator')], default='homeowner', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('floor_type', models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor'), ('basement', 'Basement')], max_length=20)),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'db_table': 'floors',
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('floor_tiles', 'Floor Tiles'), ('wall_tiles', 'Wall Tiles'), ('paint', 'Paint'), ('doors', 'Doors'), ('windows', 'Windows'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('sanitary', 'Sanitary'), ('cabinets', 'Cabinets'), ('cement', 'Cement'), ('steel', 'Steel'), ('bricks', 'Bricks'), ('sand', 'Sand'), ('gravel', 'Gravel'), ('other', 'Other')], max_length=50)),
                ('quality', models.CharField(choices=[('standard', 'Standard'), ('good', 'Good'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('unit', models.CharField(default='sqft', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
                'ordering': ['category', 'quality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('dining_room', 'Dining Room'), ('guest_room', 'Guest Room'), ('study_room', 'Study Room'), ('store_room', 'Store Room'), ('balcony', 'Balcony'), ('terrace', 'Terrace'), ('garage', 'Garage'), ('other', 'Other')], max_length=50)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_attached_bathroom', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='estimation.floor')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['floor', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('construction_type', models.CharField(choices=[('gray', 'Gray Structure Only'), ('full', 'Full Construction')], max_length=20)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('plot_unit', models.CharField(default='marla', max_length=20)),
                ('plot_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('num_floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_built_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gray_structure_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finishing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lda_compliant', models.BooleanField(default=False)),
                ('compliance_notes', models.TextField(blank=True, null=True)),
                ('floor_plan_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='estimation.project'),
        ),
        migrations.CreateModel(
            name='FinishingDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('door_quantity', models.IntegerField(default=0)),
                ('window_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_projects', to='estimation.material')),
                ('doors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_projects', to='estimation.material')),
                ('electrical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_projects', to='estimation.material')),
                ('floor_tiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_tile_projects', to='estimation.material')),
                ('paint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_projects', to='estimation.material')),
                ('plumbing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plumbing_projects', to='estimation.material')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_details', to='estimation.project')),
                ('sanitary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitary_projects', to='estimation.material')),
                ('wall_tiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_tile_projects', to='estimation.material')),
                ('windows', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_projects', to='estimation.material')),
            ],
            options={
                'verbose_name': 'Finishing Detail',
                'verbose_name_plural': 'Finishing Details',
                'db_table': 'finishing_details',
            },
        ),
        migrations.CreateModel(
            name='CostHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='estimation.material')),
            ],
            options={
                'verbose_name': 'Cost History',
                'verbose_name_plural': 'Cost Histories',
                'db_table': 'cost_history',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('gray_structure', 'Gray Structure'), ('finishing', 'Finishing')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='estimation.project')),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bill of Materials',
                'db_table': 'bill_of_materials',
                'ordering': ['category', 'material'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('project', 'floor_number')},
        ),
    ]
