# Generated by Django 4.2.11 on 2026-05-17 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coverage_ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='front_setback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='marla_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_marlas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rear_setback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='side_setbacks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='cabinets',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='doors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='electrical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='floor_tiles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='paint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='plumbing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='sanitary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='wall_tiles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishingdetails',
            name='windows',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='GrayStructureDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foundation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wall_material', models.CharField(blank=True, max_length=50, null=True)),
                ('wall_thickness', models.CharField(blank=True, max_length=50, null=True)),
                ('roof_type', models.CharField(blank=True, max_length=50, null=True)),
                ('steel_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('cement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('brick_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plaster_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gray_structure_details', to='estimation.project')),
            ],
            options={
                'verbose_name': 'Gray Structure Detail',
                'verbose_name_plural': 'Gray Structure Details',
                'db_table': 'gray_structure_details',
            },
        ),
    ]
