# Generated by Django 4.2.11 on 2026-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_project_coverage_ratio_project_front_setback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('powder_room', 'Powder Room'), ('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('drawing_room', 'Drawing Room'), ('dining_room', 'Dining Room'), ('guest_room', 'Guest Room'), ('study_room', 'Study Room'), ('store_room', 'Store Room'), ('balcony', 'Balcony'), ('terrace', 'Terrace'), ('garage', 'Garage'), ('mumty', 'Mumty'), ('spiral_stairs', 'Spiral Stairs'), ('other', 'Other')], max_length=50),
        ),
    ]
