# Generated by Django 4.2.11 on 2026-06-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_price_locked',
            field=models.BooleanField(default=False, help_text='If True, price will not be overwritten by API/scraper sync'),
        ),
    ]
