# Generated by Django 4.2.11 on 2026-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_material_is_price_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='graystructuredetails',
            name='spiral_stairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_parapet_walls',
            field=models.BooleanField(default=False),
        ),
    ]
